locals {
  vpc_cidr               = "10.0.0.0/16"
  #vpc_name               = "vpc-development-example-eu-west-1"
  #vpc_name               = "vpc-${var.env}-${var.client}-eu-west-1"
  tenancy                = "shared"
  #availability_zone1     = "eu-west-1a"
  #availability_zone2     = "eu-west-1b"
  #availability_zone3     = "eu-west-1c"
  azs			 = ["us-east-1a", "us-east-1c", "us-east-1d"]
  public_subnet_cidrs	 = ["10.0.1.0/24", "10.0.2.0/24", "10.0.3.0/24"]
  public_subnet_eks_cidrs= ["10.0.11.0/24", "10.0.12.0/24", "10.0.13.0/24"]
  private_subnet_cidrs	 = ["10.0.21.0/24", "10.0.22.0/24", "10.0.23.0/24"]
  private_subnet_eks_cidrs = ["10.0.31.0/24", "10.0.32.0/24", "10.0.33.0/24"]
  private_subnet_rds_cidrs = ["10.0.41.0/24", "10.0.42.0/24", "10.0.43.0/24"]

  #subnet1_cidr           = "10.20.10.0/24"
  #subnet1_name           = "subnet-development-example-public-us-west-2-az1"
  #subnet2_cidr           = "10.20.15.0/24"
  #subnet2_name           = "subnet-development-example-public-us-west-2-az2"
  #subnet3_cidr           = "10.20.20.0/24"
  #subnet3_name           = "subnet-development-example-private-eks-us-west-2-az1"
  #subnet4_cidr           = "10.20.25.0/24"
  #subnet4_name           = "subnet-development-example-private-eks-us-west-2-az2"
  #subnet5_cidr           = "10.20.30.0/24"
  #subnet5_name           = "subnet-development-example-private-rds-us-west-2-az1"
  #subnet6_cidr           = "10.20.35.0/24"
  #subnet6_name           = "subnet-development-example-private-rds-us-west-2-az2"
  #subnet7_cidr           = "10.20.40.0/24"
  #subnet7_name           = "subnet-development-example-private-lambda-us-west-2-az1"
  #subnet8_cidr           = "10.20.45.0/24"
  #subnet8_name           = "subnet-development-example-private-lambda-us-west-2-az2"
  #subnet9_cidr           = "10.20.50.0/24"
  #subnet9_name           = "subnet-development-example-private-cache-us-west-2-az1"
  #subnet10_cidr          = "10.20.55.0/24"
  #subnet10_name          = "subnet-development-example-private-cache-us-west-2-az2"
  gw_name                = "igw-development-example-eu-west-1"
  nat_name               = "nat-development-example-eu-west-1"
  rtbprivate_name        = "rtb-development-example-private-eu-west-1"
  rtbpublic_name         = "rtb-development-example-public-eu-west-1"
  s3-flowlog-bucket-name = "development-example-vpc-flowlogs"
  flowlog_name           = "flowlogs-vpc-development-example-eu-west-1"
  env                    = "development"
  client		 = "example"
  account-id             = "000000000000"
}
module "dev_vpc" {
  source                  = "../modules/vpc/"
  vpc_cidr                = local.vpc_cidr
  #vpc_name                = local.vpc_name
  vpc_name                = "${local.client}-${local.env}-eu-west-1-vpc"
  azs                     = local.azs
  #availability_zone2     = local.availability_zone2

  public_subnet_cidrs     = local.public_subnet_cidrs
  public_subnet_eks_cidrs = local.public_subnet_eks_cidrs
  private_subnet_cidrs    = local.private_subnet_cidrs
  private_subnet_eks_cidrs= local.private_subnet_eks_cidrs
  private_subnet_rds_cidrs= local.private_subnet_rds_cidrs
  #subnet1_cidr           = local.subnet1_cidr
  #subnet1_name           = local.subnet1_name
  #subnet2_cidr           = local.subnet2_cidr
  #subnet2_name           = local.subnet2_name
  #subnet3_cidr           = local.subnet3_cidr
  #subnet3_name           = local.subnet3_name
  #subnet4_cidr           = local.subnet4_cidr
  #subnet4_name           = local.subnet4_name
  #subnet5_cidr           = local.subnet5_cidr
  #subnet5_name           = local.subnet5_name
  #subnet6_cidr           = local.subnet6_cidr
  #subnet6_name           = local.subnet6_name
  #subnet7_cidr           = local.subnet7_cidr
  #subnet7_name           = local.subnet7_name
  #subnet8_cidr           = local.subnet8_cidr
  #subnet8_name           = local.subnet8_name
  #subnet9_cidr           = local.subnet9_cidr
  #subnet9_name           = local.subnet9_name
  #subnet10_cidr          = local.subnet10_cidr
  #subnet10_name          = local.subnet10_name
  gw_name                = local.gw_name
  nat_name               = local.nat_name
  rtbprivate_name        = local.rtbprivate_name
  rtbpublic_name         = local.rtbpublic_name
  s3-flowlog-bucket-name = local.s3-flowlog-bucket-name
  flowlog_name           = local.flowlog_name
}
